import { useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import logo from "../assets/Logo.png";
import jsPDF from "jspdf";
import {
  FaArrowLeft,
  FaHistory,
  FaSearch,
  FaFileAlt,
  FaCalendarAlt,
  FaBriefcase,
  FaStar,
  FaClipboardList,
  FaEye,
  FaDownload,
  FaTrashAlt
} from "react-icons/fa";

function History({ darkMode }) {
  const navigate = useNavigate();

  const [search, setSearch] = useState("");
  
const [historyItems, setHistoryItems] = useState([]);

const [showDeletePopup, setShowDeletePopup] = useState(false);

const [selectedResume, setSelectedResume] = useState(null);

  const [isMobile, setIsMobile] = useState(
    window.innerWidth < 768
  );

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth < 768);
    };

    window.addEventListener(
      "resize",
      handleResize
    );

    return () =>
      window.removeEventListener(
        "resize",
        handleResize
      );
  }, []);

useEffect(() => {
  const savedHistory =
    JSON.parse(localStorage.getItem("resumeHistory")) || [];

  setHistoryItems(savedHistory);
}, []);

  const confirmDelete = () => {
  setHistoryItems(
    historyItems.filter(
      (item) => item.id !== selectedResume.id
    )
  );

  setShowDeletePopup(false);

  setSelectedResume(null);
};

const filteredHistory = historyItems.filter((item) =>
  item.file
    .toLowerCase()
    .includes(search.toLowerCase())
);

const downloadHistoryReport = (item) => {
  const doc = new jsPDF("p", "mm", "a4");

  // Current Date & Time
  const now = new Date();

  const date = now.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });

  const time = now.toLocaleTimeString([], {
    hour: "2-digit",
    minute: "2-digit",
  });

  // History Data
  const summary = item.summary || "Summary not available.";
  const skills = item.skills || [];
  const suggestions = item.suggestions || [];
  const missingSkills = item.missingSkills || [];
  const score = item.score || 0;
  const role = item.role || "Not Predicted";
  const mode = item.mode || "resume";
  const resumeFile = item.file || "Uploaded Resume";

  const reportTitle =
    mode === "resume"
      ? "Professional Resume Analysis Report"
      : "Professional Job Match Report";

  const reportType =
    mode === "resume"
      ? "Resume Analysis"
      : "Resume + Job Analysis";

  // Section title helper
  const addSectionTitle = (title, y) => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235);
    doc.text(title, 20, y);

    doc.setDrawColor(37, 99, 235);
    doc.line(20, y + 3, 190, y + 3);

    doc.setTextColor(0);
  };

  // ===== Cover =====

  doc.addImage(
    logo,
    "PNG",
    87,
    15,
    36,
    36
  );

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("ResuScan", 105, 60, {
    align: "center",
  });

  doc.setFontSize(17);
  doc.setFont("helvetica", "normal");
  doc.text(reportTitle, 105, 72, {
    align: "center",
  });

  doc.setDrawColor(37, 99, 235);
  doc.line(20, 82, 190, 82);

  doc.setFontSize(13);

  doc.setFont("helvetica", "bold");
  doc.text("Resume File:", 20, 105);

  doc.setFont("helvetica", "normal");
  doc.text(resumeFile, 60, 105);

  doc.setFont("helvetica", "bold");
  doc.text("Generated On:", 20, 120);

  doc.setFont("helvetica", "normal");
  doc.text(`${date} | ${time}`, 60, 120);

  doc.setFont("helvetica", "bold");
  doc.text("Report Type:", 20, 135);

  doc.setFont("helvetica", "normal");
  doc.text(reportType, 60, 135);

  doc.line(20, 150, 190, 150);

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(120);

  doc.text(
    "Generated by ResuScan • © 2026 ResuScan",
    105,
    285,
    { align: "center" }
  );

  // ===== Report Page =====

  doc.addPage();

  let y = 20;

  // Summary
  addSectionTitle("Resume Summary", y);
  y += 12;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  const summaryLines = doc.splitTextToSize(
    summary,
    170
  );

  doc.text(summaryLines, 20, y);

  y += summaryLines.length * 6 + 10;

  // Skills
  addSectionTitle("Skills Extracted", y);
  y += 12;

  doc.setFontSize(11);

  skills.forEach((skill) => {
    doc.text("• " + skill, 22, y);
    y += 7;
  });

  y += 5;

  // Score
  addSectionTitle(
    mode === "resume"
      ? "Resume Quality Score"
      : "Job Quality Score",
    y
  );

  y += 12;

  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(`${score}%`, 20, y);

  y += 15;

  // Dynamic Section
  if (mode === "resume") {

    addSectionTitle(
      "Predicted Career Role",
      y
    );

    y += 12;

    doc.setFontSize(12);
    doc.text(role, 20, y);

    y += 15;

  } else {

    addSectionTitle(
      "Skill Gap Analysis",
      y
    );

    y += 12;

    missingSkills.forEach((skill) => {
      doc.text("• " + skill, 20, y);
      y += 7;
    });

    y += 10;
  }

  // Suggestions
  addSectionTitle(
    "Resume Suggestions",
    y
  );

  y += 12;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);

  suggestions.forEach((suggestion) => {

    const lines = doc.splitTextToSize(
      "• " + suggestion,
      165
    );

    doc.text(lines, 22, y);

    y += lines.length * 6 + 2;
  });

  // Download
  doc.save("ResuScan_Report.pdf");
};

  return (
    <div
      style={{
        minHeight: "100vh",
width: "100%",
paddingBottom: "40px",
        background: darkMode
          ? "linear-gradient(135deg,#020817 0%,#08152F 25%,#102A6B 65%,#2563EB 100%)"
          : "linear-gradient(135deg,#0f172a,#1e3a8a,#2563eb)",
        fontFamily: "Segoe UI, sans-serif"
      }}
    >
      {/* HEADER */}

      <div
        style={{
          background: darkMode
            ? "#000000"
            : "#ffffff",
          padding: "7px 30px",
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          borderBottom: darkMode
            ? "1px solid #1f2937"
            : "1px solid #e5e7eb",
          boxShadow: darkMode
            ? "0 2px 10px rgba(0,0,0,.5)"
            : "0 2px 10px rgba(0,0,0,.08)"
        }}
      >
        <img
          src={logo}
          alt="Logo"
          style={{
            width: isMobile
              ? "140px"
              : "180px",
            height: "auto"
          }}
        />

        <button
          onClick={() => navigate("/upload")}
          style={{
            display: "flex",
            alignItems: "center",
            gap: "8px",
            background: "none",
            border: "none",
            cursor: "pointer",
            color: darkMode
              ? "#ffffff"
              : "#111827",
            fontWeight: "600",
            fontSize: "16px"
          }}
        >
          <FaArrowLeft />
          Back
        </button>
      </div>

      {/* BODY */}

      <div
        style={{
          maxWidth: "1100px",
          margin: "40px auto",
          padding: isMobile
            ? "20px"
            : "7px"
        }}
      >
        {/* TITLE */}

        <h1
          style={{
            color: "#ffffff",
            textAlign: "center",
            fontSize: isMobile
              ? "32px"
              : "42px",
            marginBottom: "12px"
          }}
        >
          <FaHistory
            style={{
              marginRight: "15px"
            }}
          />
          Resume History
        </h1>

        <p
          style={{
            textAlign: "center",
            color: "#d1d5db",
            fontSize: "17px",
            marginBottom: "40px"
          }}
        >
          View all your previously analyzed resumes.
        </p>

        {/* SEARCH BAR */}

        <div
          style={{
            position: "relative",
            marginBottom: "40px"
          }}
        >
          <FaSearch
            style={{
              position: "absolute",
              top: "18px",
              left: "18px",
              color: "#64748b"
            }}
          />

          <input
            type="text"
            placeholder="Search your resume..."
            value={search}
            onChange={(e)=>{
setSearch(e.target.value);
}}
            style={{
              width: "100%",

              padding:
                "16px 16px 16px 50px",

              borderRadius: "15px",

              border: "none",

              outline: "none",

              fontSize: "16px",

              background: darkMode
                ? "#111827"
                : "#ffffff",

              color: darkMode
                ? "#ffffff"
                : "#111827",

              boxShadow:
                "0 10px 20px rgba(0,0,0,.12)"
            }}
          />
        </div>
{filteredHistory.length > 0 ? (

<div
  style={{
    display: "grid",

    gridTemplateColumns: isMobile
      ? "1fr"
      : "1fr 1fr",

    gap: "25px"
  }}
>

{filteredHistory.map((item) => (
  <div
  key={item.id}
  style={{
    background: darkMode ? "#111827" : "#ffffff",
    borderRadius: "22px",
    padding: "24px",
    boxShadow: "0 12px 28px rgba(0,0,0,.12)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    height: "340px",
    overflow: "hidden",
    transition: ".3s"
  }}
>
  {/* FILE */}

  <div>

    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "12px",
        marginBottom: "20px"
      }}
    >
      <FaFileAlt
        color="#2563eb"
        size={22}
      />

      <h2
        style={{
          margin: 0,
          fontSize: "18px",
          color: darkMode ? "#fff" : "#111827",
          overflow: "hidden",
          whiteSpace: "nowrap",
          textOverflow: "ellipsis",
          width: "100%"
        }}
        title={item.file}
      >
        <span title={item.file}>
    {item.file}
</span>
      </h2>

    </div>

    {/* DATE */}

    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "10px",
        marginBottom: "15px"
      }}
    >
      <FaCalendarAlt color="#10b981" />

      <span
        style={{
          color: darkMode ? "#d1d5db" : "#475569"
        }}
      >
        {item.date}
      </span>

    </div>

    {/* ROLE */}

    <div
      style={{
        display: "flex",
        alignItems: "flex-start",
        gap: "10px",
        marginBottom: "15px"
      }}
    >
      <FaBriefcase color="#8b5cf6" />

      <div>

        <div
          style={{
            fontWeight: "600",
            color: darkMode ? "#fff" : "#111827"
          }}
        >
          {item.mode === "resume"
            ? "Predicted Career Role"
            : "Best Job Match"}
        </div>

        <div
          style={{
            marginTop: "3px",
            color: "#2563eb",
            fontWeight: "600"
          }}
        >
          {item.role}
        </div>

      </div>

    </div>

    {/* SCORE */}

    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "10px",
        marginBottom: "15px"
      }}
    >
      <FaStar color="#f59e0b" />

      <span
        style={{
          color: darkMode ? "#d1d5db" : "#475569"
        }}
      >
        <strong>
          {item.mode === "resume"
            ? "Resume Quality Score"
            : "Job Match Score"}
        </strong>

        {" : "}

        {item.ats}
      </span>

    </div>

    {/* SUMMARY */}

    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "10px"
      }}
    >
      <FaClipboardList color="#ec4899" />

      <span
        style={{
          color: darkMode ? "#d1d5db" : "#475569"
        }}
      >
        <strong>Summary :</strong> Available
      </span>

    </div>

  </div>

  <hr
    style={{
      margin: "25px 0",
      borderColor: darkMode ? "#374151" : "#e5e7eb"
    }}
  />

  {/* BUTTONS */}

  <div
    style={{
      display: "flex",
      justifyContent: "space-between",
      gap: "10px"
    }}
  >

    {/* VIEW */}

    <button
  onClick={() =>
    navigate("/result", {
      state: {
        historyData: item,
        fromHistory: true,
      },
    })
  }
  style={{
    flex: 1,
    background: "#22c55e",
    color: "#fff",
    border: "none",
    padding: "12px",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
  }}
>
  <FaEye />
  View
</button>

    {/* DOWNLOAD */}

<button
  onClick={() => downloadHistoryReport(item)}
  style={{
    flex: 1,
    background: "#2563eb",
    color: "#fff",
    border: "none",
    padding: "12px",
    borderRadius: "10px",
    cursor: "pointer",
    fontWeight: "600",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
  }}
>
  <FaDownload />
  Download
</button>

    {/* DELETE */}

    <button
      onClick={() => {
        setSelectedResume(item);
        setShowDeletePopup(true);
      }}
      style={{
        flex: 1,
        background: "#ef4444",
        color: "#fff",
        border: "none",
        padding: "12px",
        borderRadius: "10px",
        cursor: "pointer",
        fontWeight: "600"
      }}
    >
      <FaTrashAlt /> Delete
    </button>

  </div>

</div>
))}
</div>
) : (

<div
  style={{
    background: darkMode
      ? "#111827"
      : "#ffffff",
    borderRadius: "25px",
    padding: "70px 30px",
    textAlign: "center",
    boxShadow:
      "0 10px 25px rgba(0,0,0,.12)"
  }}
>

<h1
  style={{
    fontSize: "70px",
    marginBottom: "20px"
  }}
>
📂
</h1>

<h2
  style={{
    color: darkMode
      ? "#ffffff"
      : "#111827"
  }}
>
No Resume History Yet
</h2>

<p
  style={{
    color: darkMode
      ? "#d1d5db"
      : "#6b7280",

    marginBottom: "35px"
  }}
>
Analyze your first resume to see it here.
</p>

<button

onClick={() => navigate("/upload")}

style={{
background:
"linear-gradient(to right,#2563eb,#8b5cf6)",
color:"#fff",
border:"none",
padding:"14px 35px",
borderRadius:"12px",
cursor:"pointer",
fontWeight:"600",
fontSize:"16px"
}}

>
Go To Upload
</button>

</div>

)}
      </div>
     {showDeletePopup && (
  <div
    style={{
      position: "fixed",
      top: 0,
      left: 0,
      width: "100%",
      height: "100%",
      background: "rgba(0,0,0,.55)",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9999
    }}
  >
    <div
      style={{
        width: isMobile ? "90%" : "450px",
        background: darkMode ? "#111827" : "#ffffff",
        borderRadius: "22px",
        padding: "35px",
        textAlign: "center",
        boxShadow: "0 20px 40px rgba(0,0,0,.35)"
      }}
    >
      <FaTrashAlt
        size={55}
        color="#ef4444"
      />

      <h2
        style={{
          marginTop: "18px",
          color: darkMode ? "#ffffff" : "#111827"
        }}
      >
        Delete Resume
      </h2>

      <p
        style={{
          color: darkMode ? "#d1d5db" : "#6b7280",
          marginTop: "15px",
          lineHeight: "28px"
        }}
      >
        Are you sure you want to delete

        <br />

        <b>{selectedResume?.file}</b> ?
      </p>

      <div
        style={{
          display: "flex",
          gap: "15px",
          marginTop: "35px"
        }}
      >
        <button
          onClick={() => {
            setShowDeletePopup(false);
            setSelectedResume(null);
          }}
          style={{
            flex: 1,
            padding: "14px",
            background: "#6b7280",
            color: "#ffffff",
            border: "none",
            borderRadius: "12px",
            cursor: "pointer",
            fontWeight: "600"
          }}
        >
          Cancel
        </button>

        <button
          onClick={confirmDelete}
          style={{
            flex: 1,
            padding: "14px",
            background:
              "linear-gradient(to right,#ef4444,#dc2626)",
            color: "#ffffff",
            border: "none",
            borderRadius: "12px",
            cursor: "pointer",
            fontWeight: "600"
          }}
        >
          Delete
        </button>
      </div>
    </div>
  </div>
)}
    </div>
  );
}

export default History;